# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 837e73515d96c6a4b7e70b96b67cbd9ae318a0847cc855c9c9e26a2a9ae7391656f4dfb1b9796da417840c7109716b15576330a2a8ce0f08da3bcdcef1cf63f5

test:
  secret_key_base: 27ed4f8225e3b49fd8b775823df67f42330da7405cf2d9415534e5d06d7e4f51a1ea178c874912b76c8e30313a8c0350e8499d2c64b7136f09aab9ab2b2b62f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
